services:
  benchi-conduit:
    image: 'ghcr.io/conduitio/conduit:v0.13.2'
    container_name: benchi-conduit
    networks:
      - benchi
    ports:
      - '8080:8080'
    environment:
      CONDUIT_LOG_FORMAT: json
    volumes:
      - ./conduit-scripts:/scripts
networks:
  benchi:
    external: true
