services:
  benchi-conduit:
    environment:
      CONDUIT_PREVIEW_PIPELINE_ARCH_V2: true # Using latest architecture
    volumes:
      # mount path is relative to the location of the original docker-compose file
      - ../cdc/conduit/pipeline.yml:/app/pipelines/pipeline.yml
