services:
  benchi-postgres:
    image: debezium/postgres:16
    container_name: benchi-postgres
    networks:
      - benchi
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: meroxauser
      POSTGRES_PASSWORD: meroxapass
      POSTGRES_DB: meroxadb
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "meroxadb", "-U", "meroxauser"]
      interval: 10s
      timeout: 30s
      retries: 5
networks:
  benchi:
    external: true
